package com.redditdiscord.service;

import com.redditdiscord.client.DiscordClient;
import com.redditdiscord.model.AnalysisResult;
import com.redditdiscord.model.EconomicScore;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.time.ZoneId;
import java.time.format.DateTimeFormatter;

@Slf4j
@Service
@RequiredArgsConstructor
public class DiscordNotificationService {

    private final DiscordClient discordClient;

    @Value("${discord.dm-user-id}")
    private String dmUserId;

    @Value("${discord.enabled:true}")
    private boolean enabled;

    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm z").withZone(ZoneId.of("Asia/Shanghai"));

    public void sendAnalysisDm(AnalysisResult result) {
        if (!enabled) {
            log.info("Discord notifications disabled, skipping DM");
            return;
        }

        if ("your-discord-user-id".equals(dmUserId)) {
            log.warn("Discord DM user ID not configured. Set DISCORD_DM_USER_ID env var.");
            return;
        }

        log.info("Sending analysis DM to Discord user {}", dmUserId);

        try {
            String channelId = discordClient.createDmChannel(dmUserId);
            if (channelId == null) {
                log.error("Could not create DM channel");
                return;
            }

            String message = formatDiscordMessage(result);
            discordClient.sendMessage(channelId, message);
            log.info("Analysis DM sent successfully");
        } catch (Exception e) {
            log.error("Failed to send Discord DM: {}", e.getMessage(), e);
        }
    }

    private String formatDiscordMessage(AnalysisResult result) {
        EconomicScore score = result.getEconomicScore();
        String trendingEmoji;

        StringBuilder sb = new StringBuilder();
        sb.append("# China-America Economic Analysis\n");
        sb.append(String.format("**Generated:** %s | **ID:** `%s`\n\n", DATE_FMT.format(result.getGeneratedAt()), result.getId()));

        // Economic score summary
        sb.append("## Economic Sentiment\n\n");

        // China score bar
        String chinaBar = buildScoreBar(score.getChinaScore());
        String chinaEmoji = getTrendingEmoji(score.getChinaTrending());
        sb.append(String.format("**China** %s **%s** (%d/100)\n%s\n\n",
                chinaEmoji, score.getChinaTrending(), score.getChinaScore(), chinaBar));

        // America score bar
        String usBar = buildScoreBar(score.getAmericaScore());
        String usEmoji = getTrendingEmoji(score.getAmericaTrending());
        sb.append(String.format("**America** %s **%s** (%d/100)\n%s\n\n",
                usEmoji, score.getAmericaTrending(), score.getAmericaScore(), usBar));

        // Summary
        sb.append("## Summary\n");
        sb.append(score.getSummary()).append("\n\n");

        if (score.getKeyFactors() != null && !score.getKeyFactors().isBlank()) {
            sb.append("**Key Factors:** ").append(score.getKeyFactors()).append("\n\n");
        }

        // Top channels
        sb.append("## Top Related Subreddits\n");
        for (int i = 0; i < result.getTopChannels().size(); i++) {
            AnalysisResult.RedditChannelSummary ch = result.getTopChannels().get(i);
            sb.append(String.format("%d. **%s** (%,d members)\n   %s\n",
                    i + 1, ch.getName(), ch.getSubscribers(), ch.getRelevance()));
        }
        sb.append("\n");

        // Top posters
        sb.append("## Top Posters & AI Summaries\n");
        for (int i = 0; i < result.getTopPosters().size(); i++) {
            AnalysisResult.PosterSummary p = result.getTopPosters().get(i);
            sb.append(String.format("%d. **u/%s** in %s (Score: %d)\n   %s\n   %s\n",
                    i + 1, p.getAuthor(), p.getSubreddit(), p.getScore(),
                    p.getAiSummary(), p.getPostUrl()));
        }

        sb.append("\n---\n*Generated by Reddit-Discord Bot*");
        return sb.toString();
    }

    private String buildScoreBar(int score) {
        int filled = score / 10;
        int empty = 10 - filled;
        if (score <= 40) {
            return "[" + "█".repeat(filled) + "░".repeat(empty) + "]";
        } else if (score <= 60) {
            return "[" + "█".repeat(filled) + "░".repeat(empty) + "]";
        } else {
            return "[" + "█".repeat(filled) + "░".repeat(empty) + "]";
        }
    }

    private String getTrendingEmoji(String trending) {
        return switch (trending.toUpperCase()) {
            case "BULLISH" -> "📈";
            case "BEARISH" -> "📉";
            default -> "📊";
        };
    }
}
